export const CONFIG = {
  API_URL: process.env.NEXT_PUBLIC_API_BASE_URL,
  SANCTUM_URL: process.env.NEXT_PUBLIC_SANCTUM_BASE_URL,
  REVERB_APP_KEY: process.env.NEXT_PUBLIC_REVERB_APP_KEY!,
  REVERB_HOST: process.env.NEXT_PUBLIC_REVERB_HOST,
  REVERB_PORT: Number(process.env.NEXT_PUBLIC_REVERB_PORT),
  REVERB_AUTH_END_POINT: `${process.env.NEXT_PUBLIC_API_BASE_URL}/broadcasting/auth`,
  NETSUITE_STORAGE_URL: process.env.NEXT_PUBLIC_NETSUITE_STORAGE_BASE_URL,
  STORAGE_URL: process.env.NEXT_PUBLIC_STORAGE_BASE_URL,
};
