FROM php:8.4-fpm

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip \
    git \
    curl \
    npm \
    libzip-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    autoconf \
    pkg-config \
    && docker-php-ext-configure zip \
    && docker-php-ext-install pdo pdo_mysql zip gd

# ✅ Install Redis extension
RUN pecl install redis \
    && docker-php-ext-enable redis

RUN echo "upload_max_filesize=100M" > /usr/local/etc/php/conf.d/uploads.ini && \
echo "post_max_size=100M" >> /usr/local/etc/php/conf.d/uploads.ini
# Set working directory
WORKDIR /var/www

# Copy Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# Copy application code
COPY . /var/www
COPY . .

RUN docker-php-ext-install sockets

# Build frontend assets
RUN npm install && npm run build

# Install PHP dependencies (prod only)
RUN composer install --no-dev --optimize-autoloader

# Set PHP upload limits
RUN echo "upload_max_filesize=100M" > /usr/local/etc/php/conf.d/uploads.ini && \
    echo "post_max_size=100M" >> /usr/local/etc/php/conf.d/uploads.ini

# Set correct permissions
RUN chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache

# Expose port
EXPOSE 7040

# Start PHP-FPM
CMD ["php-fpm"]
