name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check changed folders
        id: changes
        shell: powershell
        run: |
          $CHANGED_FILES = git diff --name-only "${{ github.event.before }}" "${{ github.sha }}"

          Write-Host "Changed files:"
          Write-Host $CHANGED_FILES

          if ($CHANGED_FILES -match "^server/") {
            "server=true" >> $env:GITHUB_OUTPUT
          } else {
            "server=false" >> $env:GITHUB_OUTPUT
          }

          if ($CHANGED_FILES -match "^client/") {
            "client=true" >> $env:GITHUB_OUTPUT
          } else {
            "client=false" >> $env:GITHUB_OUTPUT
          }

      - name: Set up SSH
        if: steps.changes.outputs.server == 'true' || steps.changes.outputs.client == 'true'
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.GANA }}

      - name: Deploy Server

      
        if: steps.changes.outputs.server == 'true'
        run: bash /home/webserver/scripts/deploy_scripts/ticketing_v2_server.sh

      - name: Deploy Client
        if: steps.changes.outputs.client == 'true'
        run: bash /home/webserver/scripts/deploy_scripts/ticketing_v2_client.sh