name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check changed folders
        id: changes
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})

          echo "Changed files:"
          echo "$CHANGED_FILES"

          if echo "$CHANGED_FILES" | grep -q "^server/"; then
            echo "server=true" >> $GITHUB_OUTPUT
          else
            echo "server=false" >> $GITHUB_OUTPUT
          fi

          if echo "$CHANGED_FILES" | grep -q "^client/"; then
            echo "client=true" >> $GITHUB_OUTPUT
          else
            echo "client=false" >> $GITHUB_OUTPUT
          fi

      - name: Set up SSH
        if: steps.changes.outputs.server == 'true' || steps.changes.outputs.client == 'true'
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.GANA }}

      - name: Deploy Server

      
        if: steps.changes.outputs.server == 'true'
        run: bash /home/webserver/scripts/deploy_scripts/ticketing_v2_server.sh

      - name: Deploy Client
        if: steps.changes.outputs.client == 'true'
        run: bash /home/webserver/scripts/deploy_scripts/ticketing_v2_client.sh